### PR TITLE
refs added code to com InitializeSecurity

### PR DESCRIPTION
**Pull request by patilsanty**
Added support for CoInitializeSecurity api of COM, which can be used to override both computer-wide access permissions and application-specific access permissions, but not to override the computer-wide restriction policy.

### CODE REVIEW

**Comment by patilsanty** [comment]
@mattn @jacobsantos Please review the pull request. This is required for my project in order to utilize go-ole package.

**Comment by jacobsantos** [comment]
Looks okay. I looked up why the global and I am guessing it is from the notes that the function will be called no more than once. I am unable to verify the code works. I am willing to merge as it should be safe and not affect other parts of the code.

**Comment by jacobsantos** [comment]
@mattn @patilsanty I think this should be safe to merge. It is unfortunate that the CI is down to verify automatically.

**Comment by patilsanty** [comment]
@jacobsantos Thank you. When can the CI build will be up?

**Comment by jacobsantos** [comment]
@patilsanty There is an build error.

```
# golang.org/x/tools/internal/gocommand
c:\gopath\pkg\mod\golang.org\x\tools@v0.11.0\internal\gocommand\invoke.go:399:62: undefined: os.ErrProcessDone
note: module requires Go 1.18
```

it looks like the build is using Go 1.12. Please submit something that works with Go 1.12.

**Comment by jacobsantos** [comment]
It is likely that the Go version can be bumped up since Go 1.12 was EOL 4 years ago. We could probably bump that to 1.18 safely given the language backwards compatibility support.

**Comment by jacobsantos** [comment]
@patilsanty If you can submit something that supports Go 1.12 and that passes the CI, then we can get this merged.

**Comment by jacobsantos** [comment]
Passed CI check. Merging. Thanks @patilsanty

**Comment by subodh2691** [comment]
@jacobsantos Can you help me to create a tag out of this commit? I require similar changes in my codebase to work with windows snapshots, this change will help me reducing local changes in lib.

**Comment by jacobsantos** [comment]
The tag would have to be 1.3.x. I don't want to mess with 1.2 since it may upgrade those on that branch.

**Comment by jacobsantos** [comment]
1.3.0 has been released. Thank you for the help!
